### ISSUE TITLE
create_post.rb doesn't work

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-site#173]
```
$ ./create-post.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- launchy (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:4:in `<main>'

$ gem install launchy
Fetching: launchy-2.4.3.gem (100%)
Successfully installed launchy-2.4.3
Parsing documentation for launchy-2.4.3
Installing ri documentation for launchy-2.4.3
Done installing documentation for launchy after 1 seconds
1 gem installed

$ ./create-post.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chronic (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:6:in `<main>'

$ gem install chronic
Fetching: chronic-0.10.2.gem (100%)
Successfully installed chronic-0.10.2
Parsing documentation for chronic-0.10.2
Installing ri documentation for chronic-0.10.2
Done installing documentation for chronic after 1 seconds
1 gem installed

$ ./create-post.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- slop (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:7:in `<main>'

$ gem install slop
Fetching: slop-4.2.0.gem (100%)
Successfully installed slop-4.2.0
Parsing documentation for slop-4.2.0
Installing ri documentation for slop-4.2.0
Done installing documentation for slop after 0 seconds
1 gem installed

$ ./create-post.rb
./create-post.rb:15:in `<main>': undefined method `parse!' for Slop:Module (NoMethodError)
```

**Comment by mscherer** [comment]
Did setup.sh gave any errors ?

**Comment by TomasTomecek** [comment]
It worked:

```
# bundle install
...
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
# ./create-post.rb 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- launchy (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from ./create-post.rb:4:in `<main>'
```

**Comment by mscherer** [comment]
@garrett any idea ?

**Comment by jzb** [comment]
@TomasTomecek that error looks unfamiliar but it's been a while. Can you test again and see if you're still having issues?

**Comment by garrett** [comment]
Add the following line at the bottom of the Gemfile and run bundle install:

```
gem 'launchy' 
```

Then it should work. 

Then commit both Gemfile and Gemfile.lock and push the fix. 😉

**Comment by garrett** [comment]
Add `gem 'launchy'` to Gemfile, run `bundle install`, then commit Gemfile and Gemfile.lock and push the fix please.

The command should then work after running `bundle install`.

**Comment by garrett** [comment]
Add `gem 'launchy'` to Gemfile, run `bundle install`, then commit Gemfile
and Gemfile.lock and push the fix please.

The command should work after running `bundle install`. 😉

**Comment by garrett** [comment]
Okay, GitHub has some issue. Sorry for multiple replies. (Retyping them on my phone wasn't so fun.)

**Comment by TomasTomecek** [comment]
Tried that, didn't work. Tried to install the gems manually, didn't help either. I'm giving up.

```
[root@1a51e4a13216 source]# gem install -N launchy
Successfully installed launchy-2.4.3
1 gem installed
[root@1a51e4a13216 source]# ./create-post.rb
./create-post.rb:4:in `require': cannot load such file -- launchy (LoadError)
        from ./create-post.rb:4:in `<main>'
```

Feel free to close this.

**Comment by jberkus** [comment]
I'll admit that I've never used create-post.rb, nor was I actually aware of it.

**Comment by jberkus** [comment]
@garrett create_post seems to still be broken, even with the updates of the Gemfile.  See PR.

**Comment by jberkus** [comment]
So here's the problem in the container: launchy simply won't install.

```
[root@73025a4f0521 ruby]# gem install launchy
Successfully installed launchy-2.4.3
ERROR:  While executing gem ... (Gem::DocumentError)
    RDoc is not installed: cannot load such file -- rdoc/rdoc
[root@73025a4f0521 ruby]# gem list | grep launchy
[root@73025a4f0521 ruby]# 
```

**Comment by jberkus** [comment]
I'm closing this as WONTFIX.  As far as I can tell, create_post does not work and has never worked.  Removing it from the repository.

**Comment by mscherer** [comment]
Well, it work on my laptop:
```
$ ./create-post.rb 
Usage: ./create-post.rb [options] "Blog title here."
    -a, --author          Author name (default: misc)
    -d, --date            Custom datetime (default: 2016-03-25 00:03:09 CET)
    -e, --editor          Custom editor (default: vim)
    -t, --tags            Comma-separated list of tags
    -n, --no-browser      Disable browser
    -h, --help            Display this help message.
```

Now, it might be a missing deps somewhere or some wrong version (the joy of ruby).

**Comment by jberkus** [comment]
I have not been able to create a container build where it works.

**Comment by mscherer** [comment]
So, looking at it, on a fresh fedora:latest container, this do install it:
```
# dnf install rubygems ; gem install launchy
[...]
# gem list |grep launch
launchy (2.4.3)
# gem list |grep rdoc
rdoc (4.2.0)
```

On my RHEL 7 system, I also do have rdoc 4.0.0 and launchy 2.4.3 and 2.4.2.

So I guess I must do it using a complete container to reproduce the issue
